### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by attasj** [attasj/nico-eleventy#2]
- [x] clean up names / copyrights / titles
- [ ] dark styling
- [x] GitHub pages
- [x] upload more images
- [ ] separate pages/filter by medium
- [ ] bio / contact info / artist image / about page
- [ ] pipeline to build images
